### ISSUE TITLE
Have at least 1 board generate and be able to be interacted with

### ISSUE THREAD

**Issue by jochuchemon7** [NicholasMcManus/CardGame#2]
Having trouble with making the cards to turn and display the other face if the card

**Comment by NicholasMcManus** [comment]
We got the cards working to the point that you can chose 2 cards, if they are matches they stay upright and if they are not matches they revert. I added a delay using Thread.sleep for 500 ms to make sure the user has the chance to see and memorize the second card before they are flipped back over.
